name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
          
  obfuscate:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Create distribution path
        run: |
         mkdir -p distribution_path
      
      - name: Low obfuscation test
        uses: KevinRohn/github-action-javascript-obfuscator@v1
        with:
          input_path: "assets/js"
          output_path: "assets/js"
          compact: true
          log: false
          disable_console_output: true
          rename_globals: false
          options_preset: medium-obfuscation
          target: browser
